apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

commonLabels:
  app.kubernetes.io/part-of: ecommerce

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - infrastructure.yaml
  - service-template.yaml
  - ingress.yaml
