name: ecommerce_ui_kit
description: Shared UI components for ecommerce mobile apps
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ecommerce_core:
    path: ../core
  ecommerce_shared_models:
    path: ../shared_models
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
