name: seller_app
description: E-commerce Seller App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Shared packages
  ecommerce_core:
    path: ../packages/core
  ecommerce_api_client:
    path: ../packages/api_client
  ecommerce_ui_kit:
    path: ../packages/ui_kit
  ecommerce_shared_models:
    path: ../packages/shared_models

  # Routing
  go_router: ^14.2.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # UI & Utilities
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  pull_to_refresh: ^2.0.0
  fl_chart: ^0.68.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^17.0.0

  # DI
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
